# Setup

In [1]:
import boto3
import pandas as pd
import io
import tqdm

# Compare CoralNET sources in pyspacer with new images

In [2]:
s3 = boto3.client('s3')
bucket_name = '2310-coralnet-public-sources'

response = s3.list_objects_v2(
    Bucket=bucket_name,
    Delimiter='/'
)

# Get common prefixes (folders)
if 'CommonPrefixes' in response:
    folders = [prefix['Prefix'] for prefix in response['CommonPrefixes']]
    print(f"{len(folders)} Folders found:")
else:
    print("No folders found in the bucket")

580 Folders found:

In [3]:
len(folders)

580

In [4]:
labelset = set()
data = []
for source in tqdm.tqdm(folders):
    if not source.startswith('s'):
        print(source)

    file_key = f'{source}annotations.csv'

    # Get the file from S3
    try:
        s3.head_object(Bucket=bucket_name, Key=file_key)
    except s3.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            print(f"File {file_key} not found in bucket")
            continue
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
    row = [source, len(annotations_df), annotations_df['Image ID'].nunique(), annotations_df['Label ID'].nunique()]
    data.append(row)
    labelset = labelset | set(annotations_df['Label ID'].unique())

  0%|          | 2/580 [00:00<00:49, 11.71it/s]

coralnet-public-images/
File coralnet-public-images/annotations.csv not found in bucket

 37%|███▋      | 212/580 [00:23<00:40,  9.10it/s]

File s295/annotations.csv not found in bucket

 49%|████▉     | 287/580 [00:28<00:16, 17.39it/s]

File s3182/annotations.csv not found in bucket

 52%|█████▏    | 304/580 [00:30<00:23, 11.55it/s]

File s3342/annotations.csv not found in bucket

 54%|█████▍    | 313/580 [00:31<00:27,  9.88it/s]

File s3363/annotations.csv not found in bucket

 72%|███████▏  | 416/580 [00:47<00:16, 10.09it/s]

File s372/annotations.csv not found in bucket

100%|██████████| 580/580 [01:02<00:00,  9.32it/s]

In [5]:
print(f"The total number of unique labels is {len(labelset)}")

The total number of unique labels is 2245

In [6]:
coralnet_summary_df = pd.DataFrame(data, columns=['Source', 'Num Annotations', 'Num Images', 'Num Unique Labels'])
coralnet_summary_df

     Source  Num Annotations  Num Images  Num Unique Labels
0    s1073/            45000         225                 27
1    s1076/            41800         209                 28
2     s109/           197100        3942                 78
3    s1097/            16860        1686                 78
4    s1162/               25           5                  4
..      ...              ...         ...                ...
569   s841/            58200        3880                 75
570   s842/            30309         940                  3
571   s843/            56400        2820                 64
572   s921/             1860          62                 27
573   s958/             1650          55                 20

[574 rows x 4 columns]

In [7]:
print("There are a total of %d annotations across %d images (average %d annotations per image) and %d unique labels." %
      (coralnet_summary_df["Num Annotations"].sum(), coralnet_summary_df["Num Images"].sum(), 
       coralnet_summary_df["Num Annotations"].sum() / coralnet_summary_df["Num Images"].sum(), len(labelset)))

There are a total of 11066639 annotations across 421642 images (average 26 annotations per image) and 2245 unique labels.

In [8]:
s3 = boto3.client('s3')
bucket_name = 'dev-datamermaid-sm-sources'

response = s3.list_objects_v2(
    Bucket=bucket_name,
    Delimiter='/'
)
# Get common prefixes (folders)
if 'CommonPrefixes' in response:
    folders_new = [prefix['Prefix'] for prefix in response['CommonPrefixes']]
    folder = 'coralnet-public-images/'
    # List subfolders within coralnet-public-images
    paginator = s3.get_paginator('list_objects_v2')
    sub_response = {'CommonPrefixes': []}
    for page in paginator.paginate(Bucket=bucket_name, Prefix=folder, Delimiter='/'):
        if 'CommonPrefixes' in page:
            sub_response['CommonPrefixes'].extend(page['CommonPrefixes'])
    if 'CommonPrefixes' in sub_response:
        print("Subfolders in coralnet-public-images/:")
        folders_new = [prefix['Prefix'] for prefix in sub_response['CommonPrefixes']]
        folders_new = [folder.replace("coralnet-public-images/", "") for folder in folders_new]
        # for subfolder in sub_response['CommonPrefixes']:
        #     print(f"- {subfolder['Prefix']}")
    else:
        print("No subfolders found in coralnet-public-images/")
else:
    print("No folders found in the bucket")

Subfolders in coralnet-public-images/:

In [9]:
labelset2 = set()
data2 = []
for source in tqdm.tqdm(folders_new):
    if not source.startswith('s'):
        print(source)

    file_key = f'coralnet-public-images/{source}annotations.csv'

    # Get the file from S3
    try:
        s3.head_object(Bucket=bucket_name, Key=file_key)
    except s3.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            print(f"File {file_key} not found in bucket")
            continue
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
    row = [source, len(annotations_df), annotations_df['Name'].nunique(), annotations_df['Label ID'].nunique()]
    data2.append(row)
    labelset2 = labelset2 | set(annotations_df['Label ID'].unique())

  0%|          | 0/1509 [00:00<?, ?it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10,11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  1%|▏         | 19/1509 [00:02<01:43, 14.38it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  2%|▏         | 29/1509 [00:05<04:13,  5.83it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  2%|▏         | 36/1509 [00:07<05:04,  4.84it/s]

File coralnet-public-images/s1514/annotations.csv not found in bucket

  3%|▎         | 42/1509 [00:08<04:18,  5.68it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  3%|▎         | 43/1509 [00:10<12:05,  2.02it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10,13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  5%|▍         | 75/1509 [00:20<02:59,  7.97it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  6%|▌         | 94/1509 [00:24<02:57,  7.96it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  7%|▋         | 105/1509 [00:25<03:32,  6.60it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (6,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  8%|▊         | 128/1509 [00:29<02:02, 11.28it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▊         | 132/1509 [00:30<02:25,  9.44it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 134/1509 [00:30<03:23,  6.75it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1,2,3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 138/1509 [00:31<03:55,  5.81it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 142/1509 [00:32<03:48,  5.98it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 10%|█         | 153/1509 [00:33<03:01,  7.48it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5,13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 11%|█         | 160/1509 [00:35<04:58,  4.52it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 11%|█         | 161/1509 [00:36<09:18,  2.41it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 12%|█▏        | 178/1509 [00:39<02:24,  9.22it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 15%|█▍        | 225/1509 [00:46<03:32,  6.04it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 15%|█▌        | 231/1509 [01:09<34:22,  1.61s/it]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 16%|█▌        | 237/1509 [01:16<30:51,  1.46s/it]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (3,4,5,10,12,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 17%|█▋        | 257/1509 [01:20<02:07,  9.85it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 17%|█▋        | 263/1509 [01:22<05:09,  4.02it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 21%|██▏       | 323/1509 [01:27<02:37,  7.53it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 22%|██▏       | 333/1509 [01:29<02:35,  7.57it/s]

File coralnet-public-images/s3342/annotations.csv not found in bucket

 22%|██▏       | 339/1509 [01:31<02:49,  6.88it/s]

File coralnet-public-images/s3354/annotations.csv not found in bucket

 23%|██▎       | 341/1509 [01:31<02:20,  8.34it/s]

File coralnet-public-images/s3361/annotations.csv not found in bucket

/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 23%|██▎       | 345/1509 [01:33<06:55,  2.80it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 24%|██▍       | 360/1509 [01:38<04:09,  4.60it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 25%|██▍       | 374/1509 [01:44<04:53,  3.86it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 27%|██▋       | 412/1509 [01:57<06:51,  2.67it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 28%|██▊       | 429/1509 [02:06<12:17,  1.47it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 29%|██▊       | 433/1509 [02:08<08:46,  2.04it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 29%|██▉       | 434/1509 [02:09<12:52,  1.39it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 30%|██▉       | 452/1509 [02:13<01:56,  9.05it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 30%|███       | 457/1509 [02:15<03:08,  5.57it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (11,12,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 35%|███▌      | 535/1509 [02:30<01:38,  9.88it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 37%|███▋      | 557/1509 [02:35<01:48,  8.77it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 37%|███▋      | 565/1509 [02:38<02:55,  5.38it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 43%|████▎     | 647/1509 [02:51<01:08, 12.49it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 47%|████▋     | 707/1509 [03:01<01:46,  7.55it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 48%|████▊     | 731/1509 [03:06<03:15,  3.97it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 50%|█████     | 755/1509 [03:08<00:50, 15.03it/s]

File coralnet-public-images/s5013/annotations.csv not found in bucket

 61%|██████    | 913/1509 [03:28<00:48, 12.25it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 61%|██████    | 916/1509 [03:31<03:38,  2.72it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,8,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 61%|██████    | 919/1509 [03:32<03:40,  2.68it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (10,11,12,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 79%|███████▉  | 1190/1509 [04:09<00:37,  8.49it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 81%|████████  | 1224/1509 [04:16<00:53,  5.35it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 83%|████████▎ | 1252/1509 [04:20<00:33,  7.58it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 93%|█████████▎| 1403/1509 [04:44<00:12,  8.32it/s]/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 98%|█████████▊| 1472/1509 [04:53<00:01, 30.89it/s]

File coralnet-public-images/s7538/annotations.csv not found in bucket
File coralnet-public-images/s7539/annotations.csv not found in bucket
File coralnet-public-images/s7540/annotations.csv not found in bucket
File coralnet-public-images/s7541/annotations.csv not found in bucket
File coralnet-public-images/s7543/annotations.csv not found in bucket
File coralnet-public-images/s7544/annotations.csv not found in bucket
File coralnet-public-images/s7545/annotations.csv not found in bucket
File coralnet-public-images/s7546/annotations.csv not found in bucket
File coralnet-public-images/s7547/annotations.csv not found in bucket
File coralnet-public-images/s7548/annotations.csv not found in bucket
File coralnet-public-images/s7549/annotations.csv not found in bucket
File coralnet-public-images/s7550/annotations.csv not found in bucket
File coralnet-public-images/s7551/annotations.csv not found in bucket
File coralnet-public-images/s7552/annotations.csv not found in bucket
File coralnet-public-images/s7553/annotations.csv not found in bucket
File coralnet-public-images/s7554/annotations.csv not found in bucket

 99%|█████████▊| 1487/1509 [04:53<00:00, 48.69it/s]

File coralnet-public-images/s7555/annotations.csv not found in bucket
File coralnet-public-images/s7556/annotations.csv not found in bucket
File coralnet-public-images/s7559/annotations.csv not found in bucket
File coralnet-public-images/s7560/annotations.csv not found in bucket
File coralnet-public-images/s7561/annotations.csv not found in bucket
File coralnet-public-images/s7562/annotations.csv not found in bucket
File coralnet-public-images/s7563/annotations.csv not found in bucket
File coralnet-public-images/s7564/annotations.csv not found in bucket
File coralnet-public-images/s7566/annotations.csv not found in bucket
File coralnet-public-images/s7567/annotations.csv not found in bucket
File coralnet-public-images/s7568/annotations.csv not found in bucket
File coralnet-public-images/s7569/annotations.csv not found in bucket
File coralnet-public-images/s7570/annotations.csv not found in bucket
File coralnet-public-images/s7571/annotations.csv not found in bucket
File coralnet-public-images/s7572/annotations.csv not found in bucket

 99%|█████████▉| 1500/1509 [04:53<00:00, 51.52it/s]

File coralnet-public-images/s7573/annotations.csv not found in bucket
File coralnet-public-images/s7580/annotations.csv not found in bucket
File coralnet-public-images/s7584/annotations.csv not found in bucket
File coralnet-public-images/s7594/annotations.csv not found in bucket
File coralnet-public-images/s7613/annotations.csv not found in bucket
File coralnet-public-images/s7614/annotations.csv not found in bucket
File coralnet-public-images/s7629/annotations.csv not found in bucket
File coralnet-public-images/s7638/annotations.csv not found in bucket
File coralnet-public-images/s7653/annotations.csv not found in bucket
File coralnet-public-images/s7663/annotations.csv not found in bucket

/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
/tmp/ipykernel_1337223/3951974977.py:17: DtypeWarning: Columns (2,3,4,5,6,10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
100%|██████████| 1509/1509 [04:57<00:00,  5.08it/s]

In [12]:
print(f"The total number of unique labels is {len(labelset2)}")

The total number of unique labels is 3379

In [13]:
coralnet_summary_upd_df = pd.DataFrame(data2, columns=['Source', 'Num Annotations', 'Num Images', 'Num Unique Labels'])
coralnet_summary_upd_df

      Source  Num Annotations  Num Images  Num Unique Labels
0     s1073/            45000         225                 27
1     s1076/            41800         209                 28
2      s109/           198500        3970                 78
3     s1162/               25           5                  4
4     s1184/               50          10                  7
...      ...              ...         ...                ...
1458   s841/            58200        3880                 75
1459   s842/            93739        2592                  3
1460   s843/            56400        2820                 64
1461   s921/             3150         105                 27
1462   s958/             1650          55                 20

[1463 rows x 4 columns]

In [14]:
print("There are a total of %d annotations across %d images (average %d annotations per image) and %d unique labels." %
      (coralnet_summary_upd_df["Num Annotations"].sum(), coralnet_summary_upd_df["Num Images"].sum(), 
       coralnet_summary_upd_df["Num Annotations"].sum() / coralnet_summary_upd_df["Num Images"].sum(), len(labelset2)))

There are a total of 35200570 annotations across 1145143 images (average 30 annotations per image) and 3379 unique labels.

In [15]:
coralnet_comparison_df = pd.merge(coralnet_summary_df, coralnet_summary_upd_df, 
                    on='Source', 
                    how='outer',
                    suffixes=('_orig', '_upd'))
coralnet_comparison_df = coralnet_comparison_df.sort_values('Source')
coralnet_comparison_df

,Source,Num Annotations_orig,Num Images_orig,Num Unique Labels_orig,Num Annotations_upd,Num Images_upd,Num Unique Labels_upd
0,s1073/,45000.0,225.0,27.0,45000.0,225.0,27.0
1,s1076/,41800.0,209.0,28.0,41800.0,209.0,28.0
2,s109/,197100.0,3942.0,78.0,198500.0,3970.0,78.0
3,s1097/,16860.0,1686.0,78.0,NaN,NaN,NaN
4,s1162/,25.0,5.0,4.0,25.0,5.0,4.0
...,...,...,...,...,...,...,...
1482,s841/,58200.0,3880.0,75.0,58200.0,3880.0,75.0
1483,s842/,30309.0,940.0,3.0,93739.0,2592.0,3.0
1484,s843/,56400.0,2820.0,64.0,56400.0,2820.0,64.0
1485,s921/,1860.0,62.0,27.0,3150.0,105.0,27.0
1486,s958/,1650.0,55.0,20.0,1650.0,55.0,20.0

In [16]:
coralnet_comparison_df.isna().sum(axis=0)

Source                      0
Num Annotations_orig      913
Num Images_orig           913
Num Unique Labels_orig    913
Num Annotations_upd        24
Num Images_upd             24
Num Unique Labels_upd      24
dtype: int64

In [17]:
coralnet_comparison_df[coralnet_comparison_df["Num Annotations_orig"].isna()]

,Source,Num Annotations_orig,Num Images_orig,Num Unique Labels_orig,Num Annotations_upd,Num Images_upd,Num Unique Labels_upd
6,s1189/,NaN,NaN,NaN,0.0,0.0,0.0
21,s1294/,NaN,NaN,NaN,0.0,0.0,0.0
27,s1356/,NaN,NaN,NaN,0.0,0.0,0.0
38,s1545/,NaN,NaN,NaN,0.0,0.0,0.0
42,s1577/,NaN,NaN,NaN,0.0,0.0,0.0
...,...,...,...,...,...,...,...
1475,s7494/,NaN,NaN,NaN,30.0,1.0,4.0
1476,s7513/,NaN,NaN,NaN,2400.0,96.0,18.0
1477,s7519/,NaN,NaN,NaN,1575.0,63.0,6.0
1478,s7525/,NaN,NaN,NaN,60.0,2.0,4.0
1481,s82/,NaN,NaN,NaN,0.0,0.0,0.0

# Check unmapped labels

In [18]:
import requests
def initialize_coralnet_mapping(
    mapping_endpoint="https://api.datamermaid.org/v1/classification/labelmappings/?provider=CoralNet",
):
    response = requests.get(mapping_endpoint)
    data = response.json()
    labelset = data["results"]

    while data["next"]:
        response = requests.get(data["next"])
        data = response.json()
        labelset.extend(data["results"])
    label_mapping = {
        label["provider_id"]: label["benthic_attribute_name"] for label in labelset
    }
    return label_mapping

labelmapping = initialize_coralnet_mapping()

In [19]:
s3 = boto3.client('s3')
bucket_name = 'dev-datamermaid-sm-sources'

labels = []

for source in tqdm.tqdm(folders_new):
    if not source.startswith('s'):
        print(source)

    file_key = f'coralnet-public-images/{source}annotations.csv'

    # Get the file from S3
    try:
        s3.head_object(Bucket=bucket_name, Key=file_key)
    except s3.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            print(f"File {file_key} not found in bucket")
            continue
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
    labels = labels + list(annotations_df['Label ID'])

  0%|          | 0/1509 [00:00<?, ?it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10,11,13) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  1%|          | 18/1509 [00:02<02:17, 10.84it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  2%|▏         | 29/1509 [00:05<04:08,  5.95it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  2%|▏         | 36/1509 [00:08<05:09,  4.76it/s]

File coralnet-public-images/s1514/annotations.csv not found in bucket

  3%|▎         | 42/1509 [00:09<04:10,  5.85it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  3%|▎         | 43/1509 [00:10<13:49,  1.77it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10,13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  5%|▍         | 75/1509 [00:22<03:42,  6.46it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  6%|▌         | 94/1509 [00:27<03:32,  6.67it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  7%|▋         | 105/1509 [00:29<04:08,  5.64it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (6,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  8%|▊         | 128/1509 [00:34<02:26,  9.46it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5,6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▊         | 132/1509 [00:34<02:57,  7.74it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 134/1509 [00:35<04:39,  4.93it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1,2,3,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 138/1509 [00:36<05:43,  3.99it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
  9%|▉         | 142/1509 [00:37<05:36,  4.06it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 10%|█         | 153/1509 [00:39<03:05,  7.29it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5,13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 11%|█         | 160/1509 [00:41<05:32,  4.06it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 11%|█         | 161/1509 [00:42<10:05,  2.23it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 12%|█▏        | 178/1509 [00:45<02:56,  7.55it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1,3,5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 15%|█▍        | 226/1509 [00:55<04:59,  4.29it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 15%|█▌        | 232/1509 [01:18<27:23,  1.29s/it]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 16%|█▌        | 237/1509 [01:24<29:37,  1.40s/it]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (3,4,5,10,12,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 17%|█▋        | 258/1509 [01:29<04:12,  4.96it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 17%|█▋        | 264/1509 [01:32<06:31,  3.18it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 21%|██▏       | 323/1509 [01:44<05:04,  3.89it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 22%|██▏       | 332/1509 [01:47<05:07,  3.82it/s]

File coralnet-public-images/s3342/annotations.csv not found in bucket

 22%|██▏       | 337/1509 [01:48<04:21,  4.48it/s]

File coralnet-public-images/s3354/annotations.csv not found in bucket

 22%|██▏       | 339/1509 [01:48<03:32,  5.49it/s]

File coralnet-public-images/s3361/annotations.csv not found in bucket

 23%|██▎       | 341/1509 [01:48<02:59,  6.49it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 23%|██▎       | 345/1509 [01:51<07:48,  2.48it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 24%|██▍       | 360/1509 [01:57<05:57,  3.21it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 25%|██▍       | 375/1509 [02:05<06:22,  2.97it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 27%|██▋       | 412/1509 [02:24<09:25,  1.94it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 28%|██▊       | 429/1509 [02:36<15:04,  1.19it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 29%|██▊       | 433/1509 [02:38<10:47,  1.66it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 29%|██▉       | 434/1509 [02:40<15:16,  1.17it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 30%|███       | 453/1509 [02:49<08:01,  2.19it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 30%|███       | 457/1509 [02:51<08:15,  2.12it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (11,12,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 36%|███▌      | 536/1509 [03:32<06:41,  2.43it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 37%|███▋      | 558/1509 [03:43<06:32,  2.42it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 38%|███▊      | 566/1509 [03:48<06:45,  2.33it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 43%|████▎     | 648/1509 [04:27<06:58,  2.06it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 47%|████▋     | 708/1509 [04:57<05:42,  2.34it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 48%|████▊     | 731/1509 [05:08<06:36,  1.96it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 50%|████▉     | 753/1509 [05:18<04:03,  3.10it/s]

File coralnet-public-images/s5013/annotations.csv not found in bucket

 61%|██████    | 913/1509 [06:36<05:04,  1.96it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 61%|██████    | 916/1509 [06:40<07:39,  1.29it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,8,9,11) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 61%|██████    | 919/1509 [06:42<07:34,  1.30it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (10,11,12,13,14,15,16) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 79%|███████▉  | 1190/1509 [09:13<02:55,  1.82it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 81%|████████  | 1225/1509 [09:36<02:48,  1.69it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 83%|████████▎ | 1252/1509 [09:51<02:21,  1.81it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 93%|█████████▎| 1404/1509 [11:25<01:02,  1.68it/s]/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
 98%|█████████▊| 1476/1509 [12:01<00:02, 13.23it/s]

File coralnet-public-images/s7538/annotations.csv not found in bucket
File coralnet-public-images/s7539/annotations.csv not found in bucket
File coralnet-public-images/s7540/annotations.csv not found in bucket
File coralnet-public-images/s7541/annotations.csv not found in bucket
File coralnet-public-images/s7543/annotations.csv not found in bucket
File coralnet-public-images/s7544/annotations.csv not found in bucket
File coralnet-public-images/s7545/annotations.csv not found in bucket
File coralnet-public-images/s7546/annotations.csv not found in bucket
File coralnet-public-images/s7547/annotations.csv not found in bucket
File coralnet-public-images/s7548/annotations.csv not found in bucket
File coralnet-public-images/s7549/annotations.csv not found in bucket
File coralnet-public-images/s7550/annotations.csv not found in bucket
File coralnet-public-images/s7551/annotations.csv not found in bucket
File coralnet-public-images/s7552/annotations.csv not found in bucket
File coralnet-public-images/s7553/annotations.csv not found in bucket
File coralnet-public-images/s7554/annotations.csv not found in bucket
File coralnet-public-images/s7555/annotations.csv not found in bucket

 99%|█████████▉| 1493/1509 [12:01<00:00, 29.09it/s]

File coralnet-public-images/s7556/annotations.csv not found in bucket
File coralnet-public-images/s7559/annotations.csv not found in bucket
File coralnet-public-images/s7560/annotations.csv not found in bucket
File coralnet-public-images/s7561/annotations.csv not found in bucket
File coralnet-public-images/s7562/annotations.csv not found in bucket
File coralnet-public-images/s7563/annotations.csv not found in bucket
File coralnet-public-images/s7564/annotations.csv not found in bucket
File coralnet-public-images/s7566/annotations.csv not found in bucket
File coralnet-public-images/s7567/annotations.csv not found in bucket
File coralnet-public-images/s7568/annotations.csv not found in bucket
File coralnet-public-images/s7569/annotations.csv not found in bucket
File coralnet-public-images/s7570/annotations.csv not found in bucket
File coralnet-public-images/s7571/annotations.csv not found in bucket
File coralnet-public-images/s7572/annotations.csv not found in bucket
File coralnet-public-images/s7573/annotations.csv not found in bucket
File coralnet-public-images/s7580/annotations.csv not found in bucket
File coralnet-public-images/s7584/annotations.csv not found in bucket

 99%|█████████▉| 1499/1509 [12:01<00:00, 32.54it/s]

File coralnet-public-images/s7594/annotations.csv not found in bucket
File coralnet-public-images/s7613/annotations.csv not found in bucket
File coralnet-public-images/s7614/annotations.csv not found in bucket
File coralnet-public-images/s7629/annotations.csv not found in bucket
File coralnet-public-images/s7638/annotations.csv not found in bucket
File coralnet-public-images/s7653/annotations.csv not found in bucket
File coralnet-public-images/s7663/annotations.csv not found in bucket

/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
/tmp/ipykernel_1337223/3393459972.py:20: DtypeWarning: Columns (2,3,4,5,6,10) have mixed types. Specify dtype option on import or set low_memory=False.
  annotations_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
100%|██████████| 1509/1509 [12:09<00:00,  2.07it/s]

In [20]:
s3 = boto3.client('s3')
bucket_name = 'dev-datamermaid-sm-sources'

for i, source in tqdm.tqdm(enumerate(folders_new)):
    if not source.startswith('s'):
        print(source)

    file_key = f'coralnet-public-images/{source}labelset.csv'

    # Get the file from S3
    try:
        s3.head_object(Bucket=bucket_name, Key=file_key)
    except s3.exceptions.ClientError as e:
        if e.response['Error']['Code'] == '404':
            print(f"File {file_key} not found in bucket")
            continue
    obj = s3.get_object(Bucket=bucket_name, Key=file_key)
    if i==0:
        labelset_df = pd.read_csv(io.BytesIO(obj['Body'].read()))
    else:
        labelset_df = pd.concat([labelset_df, pd.read_csv(io.BytesIO(obj['Body'].read()))], ignore_index=True)

1477it [01:40, 45.21it/s]

File coralnet-public-images/s7538/labelset.csv not found in bucket
File coralnet-public-images/s7539/labelset.csv not found in bucket
File coralnet-public-images/s7540/labelset.csv not found in bucket
File coralnet-public-images/s7541/labelset.csv not found in bucket
File coralnet-public-images/s7543/labelset.csv not found in bucket
File coralnet-public-images/s7544/labelset.csv not found in bucket
File coralnet-public-images/s7545/labelset.csv not found in bucket
File coralnet-public-images/s7546/labelset.csv not found in bucket
File coralnet-public-images/s7547/labelset.csv not found in bucket
File coralnet-public-images/s7548/labelset.csv not found in bucket
File coralnet-public-images/s7549/labelset.csv not found in bucket
File coralnet-public-images/s7550/labelset.csv not found in bucket
File coralnet-public-images/s7551/labelset.csv not found in bucket
File coralnet-public-images/s7552/labelset.csv not found in bucket
File coralnet-public-images/s7553/labelset.csv not found in bucket
File coralnet-public-images/s7554/labelset.csv not found in bucket
File coralnet-public-images/s7555/labelset.csv not found in bucket

1493it [01:40, 60.21it/s]

File coralnet-public-images/s7556/labelset.csv not found in bucket
File coralnet-public-images/s7559/labelset.csv not found in bucket
File coralnet-public-images/s7560/labelset.csv not found in bucket
File coralnet-public-images/s7561/labelset.csv not found in bucket
File coralnet-public-images/s7562/labelset.csv not found in bucket
File coralnet-public-images/s7563/labelset.csv not found in bucket
File coralnet-public-images/s7564/labelset.csv not found in bucket
File coralnet-public-images/s7566/labelset.csv not found in bucket
File coralnet-public-images/s7567/labelset.csv not found in bucket
File coralnet-public-images/s7568/labelset.csv not found in bucket
File coralnet-public-images/s7569/labelset.csv not found in bucket
File coralnet-public-images/s7570/labelset.csv not found in bucket
File coralnet-public-images/s7571/labelset.csv not found in bucket
File coralnet-public-images/s7572/labelset.csv not found in bucket
File coralnet-public-images/s7573/labelset.csv not found in bucket
File coralnet-public-images/s7580/labelset.csv not found in bucket

1501it [01:40, 64.61it/s]

File coralnet-public-images/s7584/labelset.csv not found in bucket
File coralnet-public-images/s7594/labelset.csv not found in bucket
File coralnet-public-images/s7613/labelset.csv not found in bucket
File coralnet-public-images/s7614/labelset.csv not found in bucket
File coralnet-public-images/s7629/labelset.csv not found in bucket
File coralnet-public-images/s7638/labelset.csv not found in bucket
File coralnet-public-images/s7653/labelset.csv not found in bucket
File coralnet-public-images/s7663/labelset.csv not found in bucket

1509it [01:41, 14.93it/s]

In [21]:
labelset_df

       Label ID                                 Name Short Code
0           438                   Montipora capitata     Moncap
1          2182  Montipora capitata algal overgrowth  Moncap AO
2          2185          Montipora capitata bleached  Moncap BL
3          2184       Montipora capitata tissue loss  Moncap TL
4           439                 Montipora flabellata     Monfla
...         ...                                  ...        ...
73693      3356                         Water_H20_RR    WATE**R
73694      3190                         algae others         AL
73695      3345                        fleshy seawed        FS*
73696      3183                     corals:Macroalga       MA**
73697      3362                      Turf Algae Alga       TA**

[73698 rows x 3 columns]

In [27]:
coralnet_name_map = {k:v for k, v in zip(labelset_df['Label ID'], labelset_df['Name'])}

In [28]:
label_counts = pd.Series(labels).value_counts().reset_index()
label_counts.columns = ['CoralNet ID', 'Count']
label_counts = label_counts.sort_values("Count", ascending=False)
label_counts['CoralNet Name'] = label_counts['CoralNet ID'].map(lambda x: coralnet_name_map.get(x, None))
label_counts['Mermaid Name'] = label_counts['CoralNet ID'].map(lambda x: labelmapping.get(str(x), None))
label_counts

,CoralNet ID,Count,CoralNet Name,Mermaid Name
0,82,5513048,Turf algae,Turf algae
1,84,3106263,Sand,Sand
2,1348,1741948,CRED-Turf growing on hard substrate,Turf algae
3,101,1438954,CCA (crustose coralline algae),Crustose coralline algae
4,6911,1247926,Not coral,None
...,...,...,...,...
3333,4105,1,Junceella,None
3334,1519,1,Hiatella arctica,None
3335,10357,1,Odonthalia dentata,None
3336,4064,1,Nemertea,None
3337,9999,1,Encrusting brown sponge with black dots,None

In [29]:
total_annotations = label_counts['Count'].sum()
mapped_annotations = label_counts[label_counts['Mermaid Name'].notna()]["Count"].sum()
unmapped_annotations = label_counts[label_counts['Mermaid Name'].isna()]["Count"].sum()

print(f"Currently, there are {label_counts.shape[0]} labels with {total_annotations} unique coral reef annotations.")
print(f"Out of these, {label_counts['Mermaid Name'].notna().sum()} labels with {mapped_annotations} ({mapped_annotations/total_annotations:.2%}) annotations have a label mapping to Mermaid.")
print(f"The remaining, {label_counts['Mermaid Name'].isna().sum()} labels with {unmapped_annotations} ({unmapped_annotations/total_annotations:.2%}) annotations do not have a label mapping to Mermaid.")

Currently, there are 3379 labels with 35200570 unique coral reef annotations.
Out of these, 702 labels with 29889525 (84.91%) annotations have a label mapping to Mermaid.
The remaining, 2677 labels with 5311045 (15.09%) annotations do not have a label mapping to Mermaid.

In [30]:
label_counts[label_counts["Mermaid Name"].isna()]

,CoralNet ID,Count,CoralNet Name,Mermaid Name
4,6911,1247926,Not coral,None
26,2784,260039,Turfy Biotic Matrix,None
34,1871,178294,ARMS-CREP-CCA,None
35,7462,171024,Blank_tile,None
45,626,125453,PLATE,None
...,...,...,...,...
3333,4105,1,Junceella,None
3334,1519,1,Hiatella arctica,None
3335,10357,1,Odonthalia dentata,None
3336,4064,1,Nemertea,None
3337,9999,1,Encrusting brown sponge with black dots,None

In [32]:
label_counts[(label_counts["Mermaid Name"].isna())*(label_counts["Count"]>=2000)]

     CoralNet ID    Count              CoralNet Name Mermaid Name
4           6911  1247926                  Not coral         None
26          2784   260039        Turfy Biotic Matrix         None
34          1871   178294              ARMS-CREP-CCA         None
35          7462   171024                 Blank_tile         None
45           626   125453                      PLATE         None
..           ...      ...                        ...          ...
638         1723     2064                Patella sp.         None
642         7787     2033  Mytilus galloprovincialis         None
643         7576     2015         Botrylloides niger         None
644         7855     2013      Hormosiraceae banksii         None
645         7328     2002                 Mud - Bare         None

[287 rows x 4 columns]

In [35]:
label_counts[(label_counts["Mermaid Name"].isna())*(label_counts["Count"]>=2000)].to_csv("Unmapped_CoralNet_Labels_2000.csv")